# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Push tests
# run-name: ${{ github.actor }} push tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
#          - python: 2.7.18
#            plone: 4.3
#          - python: 3.7.14
#            plone: 5.2
#          - python: 3.10.11
#            plone: "6.0"
          - python: 3.13.1
            plone: "6.1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up pyenv and Python
        uses: "gabrielfalcao/pyenv-action@v18"
        with:
          default: "${{ matrix.python }}"
      - name: Setup Env
        run: |
          pip install --upgrade pip
          pip install -r requirements-${{ matrix.plone }}.txt
      - name: Cache eggs
        uses: actions/cache@v4
        env:
          cache-name: cache-eggs
        with:
          path: ~/buildout-cache/eggs
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ matrix.python }}-${{ matrix.plone }}
      - name: buildout
        run: |
          sed -ie "s#test.cfg#test-${{matrix.plone}}.cfg#" gha.cfg
          buildout -c gha.cfg annotate
          buildout -c gha.cfg
      - name: test
        run: |
          bin/test -t !robot
  coverage:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: 3.10.11
            plone: "6.0"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up pyenv and Python
        uses: "gabrielfalcao/pyenv-action@v18"
        with:
          default: "${{ matrix.python }}"
      - name: Setup Env
        run: |
          pip install --upgrade pip
          pip install -r requirements-${{matrix.plone}}.txt
          pip install -U coveralls coverage
      - name: Cache eggs
        uses: actions/cache@v4
        env:
          cache-name: cache-eggs
        with:
          path: ~/buildout-cache/eggs
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ matrix.python }}-${{ matrix.plone }}
      - name: buildout
        run: |
          sed -ie "s#test.cfg#test-${{matrix.plone}}.cfg#" gha.cfg
          buildout -c gha.cfg
      - name: code-analysis
        run: |
          bin/code-analysis
      - name: test coverage
        run: |
          coverage run bin/test -t !robot
      - name: Publish to Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls --service=github
